#!/usr/bin/env bash

HERE="$(dirname "$(readlink -f "$0")")"

export PATH=/system/bin
export CLASSPATH="$HERE/termux-daemon.apk"

exec app_process64 -Xnoimage-dex2oat / \
  $(echo "$PACKAGE_NAME" | tr / .).Main "$@"
