name: Build Release Project

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Configure Android Tools
        run: |
          SDK_ROOT="${ANDROID_SDK_ROOT:-/usr/local/lib/android/sdk}"
          D8_PATH=$(find "$SDK_ROOT/build-tools" -name d8 | sort -V | tail -n 1)

          [ -n "$D8_PATH" ] || {
            echo "d8 not found"
            exit 1
          }

          sed -i "s|^D8=.*|D8=$D8_PATH|" config.sh
          sed -i "s|^MINIFIED=.*|MINIFIED=false|" config.sh

      - name: Build project
        run: |
          chmod +x build.sh
          ./build.sh


      - name: Build Termux binary
        run: |
          mkdir -p build-output
          chmod 777 build-output

          docker run --rm \
            --user root \
            -v "$PWD:/workspace" \
            -w /workspace \
            termux/termux-docker:aarch64 \
            bash -c '
              id
              whoami
              apt update -y
              apt install -y clang

              cc -o /workspace/build-output/android-daemon src/cpp/android-daemon.c
            '

      - name: Package release
        run: |
          export RELEASE_NAME=${{ github.ref_name }}
          mkdir -p $RELEASE_NAME

          cp termux-daemon $RELEASE_NAME
          cp build-output/android-daemon $RELEASE_NAME
          cp termux-daemon.apk $RELEASE_NAME

          tar -czvf \
            termux-daemon-$RELEASE_NAME.tar.gz \
            "$RELEASE_NAME"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}

          files: |
            termux-daemon-${{ github.ref_name }}.tar.gz
