name: Build Project

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Build (${{ matrix.arch }})
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        arch:
          - arm64-v8a
          - armeabi-v7a

    permissions:
      contents: write

    env:
      VERSION: ${{ github.ref_name }}
      CMAKE_VERSION: 3.22.1
      BUILD_TOOLS_VER: 35.0.0
      ANDROID_API: 29
      NDK_VERSION: 29.0.14206865

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Install Android SDK components
        run: |
          SDKMANAGER="$(find "$ANDROID_SDK_ROOT/cmdline-tools" -type f -name sdkmanager | head -n1)"

          if [ -z "$SDKMANAGER" ]; then
            echo "sdkmanager not found"
            exit 1
          else
            echo "found sdkmanager at: $SDKMANAGER"
          fi

          yes | "$SDKMANAGER" \
            "build-tools;${BUILD_TOOLS_VER}" \
            "platforms;android-${ANDROID_API}" \
            "cmake;${CMAKE_VERSION}" \
            "ndk;${NDK_VERSION}"

      - name: Configure build
        run: |
          sed -i "s|^ANDROID_ABI=.*|ANDROID_ABI=${{ matrix.arch }}|" config.sh
          sed -i "s|^ANDROID_API=.*|ANDROID_API=${ANDROID_API}|" config.sh
          sed -i "s|^CMAKE_VERSION=.*|CMAKE_VERSION=${CMAKE_VERSION}|" config.sh
          sed -i "s|^BUILD_TOOLS_VER=.*|BUILD_TOOLS_VER=${BUILD_TOOLS_VER}|" config.sh
          sed -i "s|^ANDROID_NDK_PATH=.*|ANDROID_NDK_PATH=\$ANDROID_SDK_ROOT/ndk/${NDK_VERSION}|" config.sh

          sed -i "s|^VERSION=.*|VERSION=${VERSION}|" config.sh

      - name: Build debug
        run: |
          sed -i "s|^BUILD_TYPE=.*|BUILD_TYPE=debug|" config.sh
          chmod +x build.sh
          ./build.sh

      - name: Package debug
        run: |
          PKG="termux-daemon-${VERSION}-${{ matrix.arch }}-debug"
          mkdir "$PKG"
          cp -a build/termux-daemon-${VERSION}-${{ matrix.arch }}-debug/. "$PKG/"
          tar -cvzf "${PKG}.tar.gz" "$PKG"

      - name: Build release
        run: |
          sed -i "s|^BUILD_TYPE=.*|BUILD_TYPE=release|" config.sh
          chmod +x build.sh
          ./build.sh

      - name: Package release
        run: |
          PKG="termux-daemon-${VERSION}-${{ matrix.arch }}-release"
          mkdir "$PKG"
          cp -a build/termux-daemon-${VERSION}-${{ matrix.arch }}-release/. "$PKG/"
          tar -cvzf "${PKG}.tar.gz" "$PKG"

      - name: Upload Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            termux-daemon-${{ github.ref_name }}-${{ matrix.arch }}-debug.tar.gz
            termux-daemon-${{ github.ref_name }}-${{ matrix.arch }}-release.tar.gz
